In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/application_train.csv')

df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
cols = [
    'TARGET',
    'AMT_INCOME_TOTAL',
    'AMT_CREDIT',
    'DAYS_EMPLOYED',
    'DAYS_BIRTH',
    'CNT_CHILDREN',
    'CODE_GENDER',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'AMT_ANNUITY',        
    'REGION_POPULATION_RELATIVE', 
    'DAYS_REGISTRATION'
]

In [4]:
df = df[cols]
df.head()

,TARGET,AMT_INCOME_TOTAL,AMT_CREDIT,DAYS_EMPLOYED,DAYS_BIRTH,CNT_CHILDREN,CODE_GENDER,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,AMT_ANNUITY,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION
0,1,202500.0,406597.5,-637,-9461,0,M,Secondary / secondary special,Single / not married,N,Y,24700.5,0.018801,-3648.0
1,0,270000.0,1293502.5,-1188,-16765,0,F,Higher education,Married,N,N,35698.5,0.003541,-1186.0
2,0,67500.0,135000.0,-225,-19046,0,M,Secondary / secondary special,Single / not married,Y,Y,6750.0,0.010032,-4260.0
3,0,135000.0,312682.5,-3039,-19005,0,F,Secondary / secondary special,Civil marriage,N,Y,29686.5,0.008019,-9833.0
4,0,121500.0,513000.0,-3038,-19932,0,M,Secondary / secondary special,Single / not married,N,Y,21865.5,0.028663,-4311.0

In [5]:
print(df.shape)

(307511, 14)

In [6]:
df['DEBT_TO_INCOME'] = df['AMT_CREDIT']/df['AMT_INCOME_TOTAL']

In [7]:
df['AGE'] = ((-df['DAYS_BIRTH'])/365).round(1)

In [8]:
df['EMPLOYMENT_YEARS'] = ((-df['DAYS_EMPLOYED'])/365).round(1)

In [9]:
df['EMPLOYMENT_YEARS'] = df['EMPLOYMENT_YEARS'].replace(1000.7, None)
df['DAYS_EMPLOYED'] = df['DAYS_EMPLOYED'].replace(365243, None)

In [10]:
df = df.drop(['DAYS_BIRTH', 'DAYS_EMPLOYED', 'AMT_CREDIT'], axis=1)

In [11]:

df['EMPLOYMENT_YEARS'] = df['EMPLOYMENT_YEARS'].fillna(df['EMPLOYMENT_YEARS'].median())
df['DEBT_TO_INCOME'] = df['DEBT_TO_INCOME'].fillna(df['DEBT_TO_INCOME'].median())


print(df.isnull().sum())

TARGET                         0
AMT_INCOME_TOTAL               0
CNT_CHILDREN                   0
CODE_GENDER                    0
NAME_EDUCATION_TYPE            0
NAME_FAMILY_STATUS             0
FLAG_OWN_CAR                   0
FLAG_OWN_REALTY                0
AMT_ANNUITY                   12
REGION_POPULATION_RELATIVE     0
DAYS_REGISTRATION              0
DEBT_TO_INCOME                 0
AGE                            0
EMPLOYMENT_YEARS               0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
text_cols = ['CODE_GENDER', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 
             'FLAG_OWN_CAR', 'FLAG_OWN_REALTY']

In [15]:
for cols in text_cols:
    df[cols] = le.fit_transform(df[cols].astype(str))

In [16]:
df.head()

,TARGET,AMT_INCOME_TOTAL,CNT_CHILDREN,CODE_GENDER,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,FLAG_OWN_CAR,FLAG_OWN_REALTY,AMT_ANNUITY,REGION_POPULATION_RELATIVE,DAYS_REGISTRATION,DEBT_TO_INCOME,AGE,EMPLOYMENT_YEARS
0,1,202500.0,0,1,4,3,0,1,24700.5,0.018801,-3648.0,2.007889,25.9,1.7
1,0,270000.0,0,0,1,1,0,0,35698.5,0.003541,-1186.0,4.790750,45.9,3.3
2,0,67500.0,0,1,4,3,1,1,6750.0,0.010032,-4260.0,2.000000,52.2,0.6
3,0,135000.0,0,0,4,0,0,1,29686.5,0.008019,-9833.0,2.316167,52.1,8.3
4,0,121500.0,0,1,4,3,0,1,21865.5,0.028663,-4311.0,4.222222,54.6,8.3

In [17]:
df.to_csv('../data/clean_data.csv', index=False)